import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { createValidationEvidence, getValidationEvidence } from './api'
import type { Project, ValidationEvidence } from './api'

const categories = [[1,'Security'],[2,'Performance'],[3,'Usability'],[4,'User Acceptance']] as const
export default function ValidationPanel({ token, projects, selectedProject, selectedProjectId, canLead, onProjectChange }: { token: string; projects: Project[]; selectedProject: Project | null; selectedProjectId: string; canLead: boolean; onProjectChange: (id: string) => void }) {
  const [items, setItems] = useState<ValidationEvidence[]>([]); const [category, setCategory] = useState(1); const [result, setResult] = useState(1); const [title, setTitle] = useState(''); const [evidence, setEvidence] = useState(''); const [message, setMessage] = useState('')
  const load = () => { if (selectedProjectId) getValidationEvidence(token, selectedProjectId).then(setItems).catch((e) => setMessage(e instanceof Error ? e.message : 'Unable to load evidence.')) }
  useEffect(load, [selectedProjectId])
  async function submit(event: FormEvent) { event.preventDefault(); if (!selectedProjectId) return; try { await createValidationEvidence(token, selectedProjectId, { category, result, title, evidence }); setTitle(''); setEvidence(''); setMessage('Validation evidence recorded.'); load() } catch (e) { setMessage(e instanceof Error ? e.message : 'Unable to record evidence.') } }
  const latest = new Map<string, ValidationEvidence>(); for (const item of items) if (!latest.has(item.category)) latest.set(item.category, item)
  if (!projects.length) return <section className="panel emptyState"><h3>Create a project first</h3></section>
  return <><section className="projectPicker panel"><div><p className="eyebrow">PHASE 7 · FINAL VALIDATION</p><h3>{selectedProject?.name}</h3></div><select value={selectedProjectId} onChange={(e) => onProjectChange(e.target.value)}>{projects.map((p) => <option key={p.id} value={p.id}>{p.key} · {p.name}</option>)}</select></section>{message && <div className="notice">{message}</div>}
    <section className="validationGrid">{categories.map(([,name]) => { const item = latest.get(name.replace('User Acceptance','UserAcceptance')); return <article className="panel validationCard" key={name}><span className={`validationIcon ${item?.result.toLowerCase() ?? ''}`}>{item?.result === 'Passed' ? '✓' : item?.result === 'Failed' ? '×' : '○'}</span><div><p className="eyebrow">{name.toUpperCase()}</p><h3>{item?.result ?? 'No evidence'}</h3><p className="muted">{item?.title ?? 'Record formal validation evidence.'}</p></div></article> })}</section>
    <section className="splitLayout"><div className="panel"><div className="panelTitle"><h3>Validation evidence log</h3><span>{items.length}</span></div><div className="requirementsList">{items.map((item) => <article className="requirementCard" key={item.id}><div className="requirementTop"><span className="itemCode">{item.category}</span><span className={`pill ${item.result.toLowerCase()}`}>{item.result}</span></div><h4>{item.title}</h4><p>{item.evidence}</p><footer><span>{item.executedBy}</span><span>{new Date(item.executedAtUtc).toLocaleString()}</span></footer></article>)}</div></div>
      {canLead && <form className="panel formPanel" onSubmit={submit}><div className="panelTitle"><h3>Record validation</h3></div><label>Category<select value={category} onChange={(e) => setCategory(Number(e.target.value))}>{categories.map(([value,name]) => <option key={value} value={value}>{name}</option>)}</select></label><label>Result<select value={result} onChange={(e) => setResult(Number(e.target.value))}><option value={1}>Passed</option><option value={2}>Failed</option><option value={3}>Conditional</option></select></label><label>Title<input value={title} onChange={(e) => setTitle(e.target.value)} required /></label><label>Evidence<textarea rows={8} value={evidence} onChange={(e) => setEvidence(e.target.value)} placeholder="Procedure, result, metrics, observations, evidence reference…" required /></label><button className="primary">Record evidence</button></form>}
    </section>
  </>
}
